### ISSUE TITLE
Which parameters to change for loading own data?

### ISSUE THREAD

**Issue by spencergoff** [AntreasAntoniou/MatchingNetworks#11]
Hi, 

I have an image set of 6 classes, each containing 4 images. Exactly which parameters should I modify? I've only modified the train_one_shot_learning_matching_network.py, where I've changed batch_size to 1 (I also tried leaving it as 32), classes_per_set to 4 instead of 20, total_train_batches = 18, total_val_batches = 3, and total_test_batches = 3. Those look to me the main variables that I should need to change to work with my data, but I get various errors based on what I change these numbers to (example below). Is there anything else I should modify? 

I can successfully run this model using the default Omniglot data, but when I try to use my own data, I receive different errors depending on which parameters I have changed (I've tried many different combinations. 

On my latest iteration, here's my code in train_one_shot_learning_matching_network.py, lines 11 to 36 (which are the only lines I've modified): 

```
batch_size = 1
fce = False
classes_per_set = 4
samples_per_class = 1
continue_from_epoch = -1  # use -1 to start from scratch
epochs = 1
num_gpus = 1
logs_path = "one_shot_outputs/"
experiment_name = "one_shot_learning_embedding_{}_{}".format(samples_per_class, classes_per_set)

data = dataset.FolderDatasetLoader(num_of_gpus=num_gpus, batch_size=batch_size, image_height=100, image_width=100,
                                   image_channels=3, #RBG images have 3 color channels
                                   train_val_test_split= (18/24,3/24,3/24),#(1200/1622, 211/1622, 211/162),
                                   samples_per_iter=1, num_workers=4,
                                   data_path="datasets/toys", name="toys",
                                   index_of_folder_indicating_class=-2, reset_stored_filepaths=False,
                                   num_samples_per_class=samples_per_class, num_classes_per_set=classes_per_set)

experiment = ExperimentBuilder(data)
one_shot_omniglot, losses, c_error_opt_op, init = experiment.build_experiment(batch_size,
                                                                                     classes_per_set,
                                                                                     samples_per_class, fce)
total_train_batches = 18
total_val_batches = 3
total_test_batches = 3
```

And running 'python train_one_shot_learning_matching_network.py' in Terminal (on a Mac) yields: 

> /Users/spencer/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
6
4 5 6
data {'train': 16, 'val': 4, 'test': 4}
WARNING:tensorflow:From /Users/spencer/Documents/MatchingNetworks/one_shot_learning_network.py:75: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "/Users/spencer/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/Users/spencer/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Index out of range using input dim 0; input has only 0 dims for 'losses/strided_slice_9' (op: 'StridedSlice') with input shapes: [], [2], [2], [2] and with computed input tensors: input[3] = <1 1>.

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "train_one_shot_learning_matching_network.py", line 33, in <module>
>     samples_per_class, fce)
>   File "/Users/spencer/Documents/MatchingNetworks/experiment_builder.py", line 48, in build_experiment
>     summary, self.losses, self.c_error_opt_op = self.one_shot_omniglot.init_train()
>   File "/Users/spencer/Documents/MatchingNetworks/one_shot_learning_network.py", line 278, in init_train
>     losses = self.loss()
>   File "/Users/spencer/Documents/MatchingNetworks/one_shot_learning_network.py", line 237, in loss
>     crossentropy_loss = self.crossentropy_softmax(targets=targets, outputs=preds)
>   File "/Users/spencer/Documents/MatchingNetworks/one_shot_learning_network.py", line 269, in crossentropy_softmax
>     normOutputs = outputs - tf.reduce_max(outputs, axis=-1)[:, None]
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 588, in _slice_helper
>     name=name)
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 754, in strided_slice
>     shrink_axis_mask=shrink_axis_mask)
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5397, in strided_slice
>     name=name)
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3273, in create_op
>     compute_device=compute_device)
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3313, in _create_op_helper
>     set_shapes_for_outputs(op)
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2501, in set_shapes_for_outputs
>     return _set_shapes_for_outputs(op)
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2474, in _set_shapes_for_outputs
>     shapes = shape_func(op)
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2404, in call_with_requiring
>     return call_cpp_shape_fn(op, require_shape_fn=True)
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
>     require_shape_fn)
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
>     raise ValueError(err.message)
> ValueError: Index out of range using input dim 0; input has only 0 dims for 'losses/strided_slice_9' (op: 'StridedSlice') with input shapes: [], [2], [2], [2] and with computed input tensors: input[3] = <1 1>.

I believe my file structures is set up properly for the data loader: 
<img width="437" alt="screen shot 2018-03-22 at 7 38 39 pm" src="https://user-images.githubusercontent.com/14855088/37808885-24923f92-2e23-11e8-860d-29ee4a84df14.png">

I probably just don't understand some of the variables and how they should change based on the number of classes/images. Any help is much appreciated!

**Comment by AntreasAntoniou** [comment]
First of all you have way too small an amount of data to train any type of model using neural networks. That aside, a batch of 1 is not a very good idea. I am pretty sure using a batch of 1 might break the matching network. Try a bigger batch size, and if you want to train a model that actually can learn to infere meaningful predictions you need a larger dataset. If you had say 30 classes and 10 samples each maybe just maybe you would get something. For a truly good model 50 classes of 100 samples each would be even better.

**Comment by AntreasAntoniou** [comment]
Also here train_val_test_split= (18/24,3/24,3/24) you should set up the splits in terms of classes. so for 6 classes it should be something like 2, 2, 2. And it can only be 2 classes per set. You need more classes for val and test, not just 1.

**Comment by spencergoff** [comment]
I can find more data, I just want to make sure this will work for my purposes first. (I want to have one picture of each stuffed animal that a kid has, then store each picture with the animal's name, e.g. Fido, then be able to take a picture of one of the animals and have its name given to me.) 

Does the batch_size affect the value of total_train_batches, etc.? 

Also, I don't think I actually have a dedicated GPU on my laptop (MacBook Pro). I tried setting num_gpus = 0 but I got an error. Could this be a problem? 

I'll post some results of altering the batch_size and train_val_test_split below, thanks the for help!

**Comment by spencergoff** [comment]
(All of my code below line 38 is exactly the same as the original.)

When I set batch_size = 10 and changed nothing else: 

> Traceback (most recent call last):                                                                    | 0/3 [00:00<?, ?it/s]
>   File "train_one_shot_learning_matching_network.py", line 79, in <module>
>     sess=sess)
>   File "/Users/spencer/Documents/MatchingNetworks/experiment_builder.py", line 104, in run_validation_epoch
>     augment_images=False)):
>   File "/Users/spencer/Documents/MatchingNetworks/data.py", line 373, in get_val_batches
>     for sample_id, sample_batched in enumerate(self.get_dataloader(shuffle=False)):
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 210, in __next__
>     return self._process_next_batch(batch)
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 230, in _process_next_batch
>     raise batch.exc_type(batch.exc_msg)
> ValueError: Traceback (most recent call last):
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 42, in _worker_loop
>     samples = collate_fn([dataset[i] for i in batch_indices])
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 42, in <listcomp>
>     samples = collate_fn([dataset[i] for i in batch_indices])
>   File "/Users/spencer/Documents/MatchingNetworks/data.py", line 313, in __getitem__
>     self.get_set(self.current_dataset_name, seed=self.init_seed[self.current_dataset_name] + idx, augment_images=self.augment_images)
>   File "/Users/spencer/Documents/MatchingNetworks/data.py", line 251, in get_set
>     size=self.num_classes_per_set, replace=False)
>   File "mtrand.pyx", line 1166, in mtrand.RandomState.choice
> **ValueError: Cannot take a larger sample than population when 'replace=False'**

 



When I set batch_size = 10 and train_val_test_split= (2,2,2):

> Traceback (most recent call last):                                                                    | 0/3 [00:00<?, ?it/s]
>   File "train_one_shot_learning_matching_network.py", line 79, in <module>
>     sess=sess)
>   File "/Users/spencer/Documents/MatchingNetworks/experiment_builder.py", line 104, in run_validation_epoch
>     augment_images=False)):
>   File "/Users/spencer/Documents/MatchingNetworks/data.py", line 373, in get_val_batches
>     for sample_id, sample_batched in enumerate(self.get_dataloader(shuffle=False)):
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 210, in __next__
>     return self._process_next_batch(batch)
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 230, in _process_next_batch
>     raise batch.exc_type(batch.exc_msg)
> ValueError: Traceback (most recent call last):
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 42, in _worker_loop
>     samples = collate_fn([dataset[i] for i in batch_indices])
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 42, in <listcomp>
>     samples = collate_fn([dataset[i] for i in batch_indices])
>   File "/Users/spencer/Documents/MatchingNetworks/data.py", line 313, in __getitem__
>     self.get_set(self.current_dataset_name, seed=self.init_seed[self.current_dataset_name] + idx, augment_images=self.augment_images)
>   File "/Users/spencer/Documents/MatchingNetworks/data.py", line 251, in get_set
>     size=self.num_classes_per_set, replace=False)
>   File "mtrand.pyx", line 1126, in mtrand.RandomState.choice

> > ValueError: a must be non-empty

> 


When I set batch_size = 10 and train_val_test_split= (2/6,2/6,2/6):


> Traceback (most recent call last):                                                                   | 0/18 [00:00<?, ?it/s]
>   File "train_one_shot_learning_matching_network.py", line 73, in <module>
>     sess=sess)
>   File "/Users/spencer/Documents/MatchingNetworks/experiment_builder.py", line 64, in run_training_epoch
>     augment_images=self.data_augmentation)):
>   File "/Users/spencer/Documents/MatchingNetworks/data.py", line 360, in get_train_batches
>     for sample_id, sample_batched in enumerate(self.get_dataloader(shuffle=True)):
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 210, in __next__
>     return self._process_next_batch(batch)
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 230, in _process_next_batch
>     raise batch.exc_type(batch.exc_msg)
> ValueError: Traceback (most recent call last):
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 42, in _worker_loop
>     samples = collate_fn([dataset[i] for i in batch_indices])
>   File "/Users/spencer/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 42, in <listcomp>
>     samples = collate_fn([dataset[i] for i in batch_indices])
>   File "/Users/spencer/Documents/MatchingNetworks/data.py", line 313, in __getitem__
>     self.get_set(self.current_dataset_name, seed=self.init_seed[self.current_dataset_name] + idx, augment_images=self.augment_images)
>   File "/Users/spencer/Documents/MatchingNetworks/data.py", line 251, in get_set
>     size=self.num_classes_per_set, replace=False)
>   File "mtrand.pyx", line 1166, in mtrand.RandomState.choice
> **ValueError: Cannot take a larger sample than population when 'replace=False'**
>

**Comment by AntreasAntoniou** [comment]
Use num GPUs as 1. Also training a matching net without a gpu will take
more than 2 days.

**Comment by spencergoff** [comment]
Okay, I can also use Amazon Sagemaker for training if necessary.

**Comment by AntreasAntoniou** [comment]
How did you structure your dataset? Is it identical to the matching network
structure?

**Comment by spencergoff** [comment]
Is this what you mean? 
<img width="290" alt="screen shot 2018-03-23 at 10 15 36 am" src="https://user-images.githubusercontent.com/14855088/37834023-41cf9428-2e83-11e8-9f45-a8b8f0021c2c.png">

**Comment by AntreasAntoniou** [comment]
Yes, that looks ok.

**Comment by spencergoff** [comment]
So do you think I should set train_val_test_split= (2,2,2) or train_val_test_split= (2/6,2/6,2/6)? Based on what the original code has I would think the latter, I have 6 classes total. Each class has exactly 4 images in it, and I set classes_per_set = 4. Hmmm....

**Comment by AntreasAntoniou** [comment]
Classes per set can't be more than the number of classes in each set. You
should use 2/6 at each split and 2 as classes per set, then up to 4 for
samples per class.

**Comment by spencergoff** [comment]
It works! I set samples_per_class = 4 and classes_per_set = 2. I assume the latter is what made it work. So classes_per_set is the number of classes in each of the training, validation, and test set?

**Comment by AntreasAntoniou** [comment]
No, classes per set is the number of.classes used per episode. It can be
any number that is less than or equal to the available classes in the
train, validation and test sets.

**Comment by spencergoff** [comment]
Ah okay. Also, if I want to take a new picture of one of these toys and return its correct class (e.g., a new picture of the same blue bunny stuffed animal that should be classified in the blue_bunny class), how exactly would I specify that?

**Comment by AntreasAntoniou** [comment]
Matching nets learn to classify using small episodes composed of randomly
chosen classes. If you want specific labels you'll need to modify the
setup. You'll need to write a new routine that scores all the learned
embedding vectors for each class and then at prediction time compare your
target images embedding to all the others, then return the class closest to
it.

**Comment by spencergoff** [comment]
Okay, I may email you at a later time with questions about getting the embedding vectors. Thanks a lot!
