### ISSUE TITLE
Hello, could you please tell me that where is the implementation of the funciton "rotate" in file data.py?

### ISSUE THREAD

**Issue by Warden7** [AntreasAntoniou/MatchingNetworks#2]

**Comment by AntreasAntoniou** [comment]
I am in the middle of updating my code this week. Please standby as I complete it. Hope it doesn't cause any issues.

**Comment by AntreasAntoniou** [comment]
Ok, the code has been updating with some improvements. Try running everything now. Also if you run any 20-way 1-shot experiments please post your results here. I am just trying to find out why my implementation is getting much higher than the paper suggests.
