### ISSUE TITLE
Performance on Omniglot

### ISSUE THREAD

**Issue by caiqi** [AntreasAntoniou/MatchingNetworks#4]
Hi, I have run your code on the Omniglot dataset. The performance is higher than the number in the paper. After 3 epochs, the 1-shot 20-way accuracy reaches 0.9615. However, when setting shuffle class to False, https://github.com/AntreasAntoniou/MatchingNetworks/blob/master/data.py#L4 , the performance drops to around 0.935. It looks that the split of train/val/test is important. If setting shuffle_class to true, the classes in test set are more likely to come from different alphabets. If setting shuffle class to False, the classes in test set are more likely to come from same alphabet than setting shuffle class to True.(assuming the classes in original data.npy is sorted by alphabets). It's obvious that within alphabet classification is more difficult than cross alphabets classification. 

Another issue is https://github.com/AntreasAntoniou/MatchingNetworks/blob/master/data.py#L95, for test/val, the augment is set to False and seems that the image won't be normalized. 

Besides, have you ever try 5-shot, 20-way and 5-shot, 5-way experiments. The paper performance shows that 20-way performance is nearly identical with 5-way, which is strange and my experiments can reach the 5-way, 5-shot performance but not the 20-way, 5-shot performance.  Thanks.

**Comment by AntreasAntoniou** [comment]
I also realised the issue with the accuracy. I was not able to find out why. In the paper they mention that they shuffle the classes, but not in what specific way, so I had no way of knowing that. If you can figure out why let me know. I fixed the normalization bug, thanks for the heads up, I have another repo which was working correctly, it was more of a code transfer issue on my part. It's now fixed. Also for the 20-way 5-shot I did try experiments and I was able to reach the scores in the paper some time ago.
