### ISSUE TITLE
maybe a data feeder bug

### ISSUE THREAD

**Issue by kinlog** [AntreasAntoniou/MatchingNetworks#5]
file: data.py -> class: OmniglotNShotDataset -> function: sample_new_batch
``` python
for i in range(self.batch_size):
            classes_idx = np.arange(data_pack.shape[0])
            samples_idx = np.arange(data_pack.shape[1])
            choose_classes = np.random.choice(classes_idx, size=self.classes_per_set, replace=False)
            choose_label = np.random.choice(self.classes_per_set, size=1)
            choose_samples = np.random.choice(samples_idx, size=self.samples_per_class+1, replace=False)

            x_temp = data_pack[choose_classes]
            x_temp = x_temp[:, choose_samples]
            y_temp = np.arange(self.classes_per_set)
            support_set_x[i] = x_temp[:, :-1]
            support_set_y[i] = np.expand_dims(y_temp[:], axis=1)
            target_x[i] = x_temp[choose_label, -1]
            target_y[i] = y_temp[choose_label]
```
I check this code carefully, and I found something unreasonable here.
You choose the classes first and then the samples, the problem here is that you always choose the same index of samples in class.
For example, after you choose 20 classes, there are 20 samples in every class, the right choice is randomly choose samples in every class, but the current code runs with choosing the i-th sample in every classes.

Waiting for your reply.

**Comment by AntreasAntoniou** [comment]
If the samples and classes axis is randomly shuffled beforehand this shouldn't make any difference in the training since the samples within a class don't have any relationships with other samples from another. So I guess this shouldn't make a difference to the network?

**Comment by AntreasAntoniou** [comment]
If you have any ideas why it would make a difference let me know.

**Comment by kinlog** [comment]
Yes, I agree with you. but the current code only shuffle the classes, so it's better to shuffle the samples at the same time. It's that so?
``` python
if shuffle_classes:
            class_ids = np.arange(self.x.shape[0])
            np.random.shuffle(class_ids)
            self.x = self.x[class_ids]
```

**Comment by kinlog** [comment]
I checked another version of Matching Network, which is randomly choose samples under every class.
source: https://github.com/zergylord/oneshot/blob/master/match_net.py

``` python
    for i in range(mb_dim):
        ind = 0
        pinds = np.random.permutation(n_samples)
        classes = np.random.choice(cur_data.shape[0],y_dim,False)
        x_hat_class = np.random.randint(y_dim)
        for j,cur_class in enumerate(classes): #each class
            example_inds = np.random.choice(cur_data.shape[1],n_samples_per_class,False)
            for eind in example_inds:
                mb_x_i[i,pinds[ind],:,:,0] = np.rot90(cur_data[cur_class][eind],np.random.randint(4))
                mb_y_i[i,pinds[ind]] = j
                ind +=1
            if j == x_hat_class:
                mb_x_hat[i,:,:,0] = np.rot90(cur_data[cur_class][np.random.choice(cur_data.shape[1])],np.random.randint(4))
                mb_y_hat[i] = j
```

**Comment by AntreasAntoniou** [comment]
Ok yes. We can shuffle the samples as well. The second method is not as efficient computationally I think. As long as we shuffle the samples every, let's say 50 batches they should be relatively random.

**Comment by kinlog** [comment]
Yes, agree with you. And really appreciate for your dedication👍.

**Comment by AntreasAntoniou** [comment]
Just added improvement.
