### ISSUE TITLE
incorrect implementation of FCE

### ISSUE THREAD

**Issue by godsme** [AntreasAntoniou/MatchingNetworks#7]
1. fce should be a seq2seq architecture with attention
2. the decoder of fce should be a uni-directional lstm instead of a bi-directional one.

**Comment by AntreasAntoniou** [comment]
I agree. The FCE component wasn't a replication that's 100% what the paper mentioned, just a fuctional re-interpretation. Would you like to provide a better version? Please feel free to do pull requests.
