### ISSUE TITLE
How to load own data

### ISSUE THREAD

**Issue by spencergoff** [AntreasAntoniou/MatchingNetworks#8]
Hi, 
     The model is excellent, and I'd like to use some of my own images instead of the Omniglot data. From what I can tell the Omniglot data is being loaded from data.npy (although I can't figure out how to view the images in this file to confirm). I assume that I need to get my own images, along with their class labels, into a file of type *.npy to use them in the model. How exactly should I do this? 

I've looked at some [documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html) for saving data as *.npy, but I'm not sure how to add in class labels. 

Any help is much appreciated!

**Comment by AntreasAntoniou** [comment]
The data is saved in shape (num_classes, num_samples, height, width, channels) so all you have to do is save your images in a .npy file with that same shape. Basically collect the images of each class and put them under the same class index in the numpy array. To save things in numpy array you just need to load them into python and contruct a numpy array then use np.save to save them

**Comment by AntreasAntoniou** [comment]
I will soon be providing a data provider that can automatically grab a folder of images that are structured as dir --> class --> samples and load everything automatically. So you can wait for that if you want.

**Comment by spencergoff** [comment]
Thanks for the quick reply! That update would be a fantastic improvement to an already great model. When do you think that will be ready?

**Comment by AntreasAntoniou** [comment]
Soonish (72 hours?)

**Comment by spencergoff** [comment]
That would be awesome, I'll just wait if that's the case. Thanks so much!

**Comment by spencergoff** [comment]
Let me know if there's anything I can do to help with the data provider :)

**Comment by AntreasAntoniou** [comment]
This is now implemented :)

**Comment by mhnatiuk** [comment]
Hi, I am trying to use data provider which you kindly implemented for us :) I have a following folder structure:
data/class_name1 (it's a string)
data/class_name2 (..)

in each folder i have samples (jpgs in different resolutions sampled from web) for each class (the dataset is inbalanced, i.e. i have sometimes 9 sometimes > 300 of examples).
Now, when I am trying to use training_one_shot_learning_matching_network.py i get following outut

``Traceback (most recent call last):
  File "train_one_shot_learning_matching_network.py", line 75, in <module>
    sess=sess)
  File "/home/mhnatiuk/Documents/code/MatchingNetworks/experiment_builder.py", line 73, in run_training_epoch
    self.learning_rate: self.current_learning_rate})
  File "/home/mhnatiuk/Documents/code/nologo.ai/env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/mhnatiuk/Documents/code/nologo.ai/env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1113, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 32, 20, 1) for Tensor 'support_set_images:0', which has shape '(1, 32, 20, 1, 224, 224, 3)' ```

which seems rather weird since it suggests that I provide a support image with **one** value and in incorrect shape. Can you kindly suggest where to look for a mistake? I can maybe fork your repo and provide some assertions?
Best regards

**Comment by AntreasAntoniou** [comment]
That looks rather weird. I'll have a quick look in a few hours.

**Comment by mhnatiuk** [comment]
Thanks. Do you need some additional info? Im in eastern Europe tz, hence
the question
W dniu śr., 28.03.2018 o 22:44 Antreas Antoniou <notifications@github.com>
napisał(a):

> That looks rather weird. I'll have a quick look in a few hours.

**Comment by AntreasAntoniou** [comment]
Which python version are you using?

**Comment by mhnatiuk** [comment]
python 3.5 and tf 1.6, compiled from source for cuda 9.1 support
W dniu czw., 29.03.2018 o 02:10 Antreas Antoniou <notifications@github.com>
napisał(a):

> Which python version are you using?
>

**Comment by AntreasAntoniou** [comment]
Thats it then. You need python 3.6

**Comment by mhnatiuk** [comment]
Ok, thanks, I’ll update you if this won’t work.
Cheers!
W dniu czw., 29.03.2018 o 02:24 Antreas Antoniou <notifications@github.com>
napisał(a):

> Thats it then. You need python 3.6
>

**Comment by AntreasAntoniou** [comment]
I am very certain this could be it, because the same error happened to me
when I used my data provider on 3.5

**Comment by aplusc98** [comment]
Hey,
I'm slightly confused about the data loader, the Omniglot dataset has images_background and images_evaluation folder and then Alphabets and then the actual character classes structure(even in the repository it has same struc.) but in the readme, you have mentioned that all the classes should be directly under the parent dataset folder, How does this work in case of the Omniglot dataset?
